# Generated by Django 6.0.6 on 2026-07-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('market_name', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=8)),
                ('entry_price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('volume', models.FloatField(help_text='Simulated lot size')),
                ('risk_pct', models.FloatField(help_text='% of paper balance risked')),
                ('signal_strength', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed_tp', 'Closed — Take Profit'), ('closed_sl', 'Closed — Stop Loss'), ('closed_manual', 'Closed — Manual')], default='open', max_length=16)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
