# Generated by Django 6.0.6 on 2026-07-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('market_name', models.CharField(max_length=64)),
                ('market_type', models.CharField(max_length=16)),
                ('direction', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Neutral', 'Neutral')], default='Neutral', max_length=8)),
                ('signal_strength', models.FloatField(default=0)),
                ('setup_quality', models.FloatField(default=0)),
                ('opportunity_score', models.FloatField(default=0)),
                ('entry_type', models.CharField(blank=True, default='', max_length=32)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=8)),
                ('price', models.FloatField()),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('atr', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('risk_reward', models.FloatField(blank=True, null=True)),
                ('model_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', '-created_at'], name='analysis_ma_symbol_7604bf_idx')],
            },
        ),
    ]
