# Generated by Django 5.0.7 on 2026-07-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsignal',
            name='structure',
            field=models.CharField(blank=True, default='Neutral', max_length=16),
        ),
    ]
