# Generated by Django 5.0.7 on 2026-07-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_marketsignal_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsignal',
            name='confirmation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketsignal',
            name='pattern',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='marketsignal',
            name='patterns_identified',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketsignal',
            name='support_resistance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='marketsignal',
            name='technical_notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
