# Generated by Django 5.0.7 on 2026-07-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_marketsignal_confirmation_count_marketsignal_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsignal',
            name='timeframe',
            field=models.CharField(default='1M', max_length=8),
        ),
    ]
