# Generated by Django 5.0.7 on 2026-07-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_marketsignal_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsignal',
            name='timeframe',
            field=models.CharField(blank=True, default='1H', max_length=8),
        ),
    ]
