# Generated by Django 5.0.7 on 2026-07-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_marketsignal_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsignal',
            name='actual_pnl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketsignal',
            name='pnl_hit',
            field=models.CharField(blank=True, choices=[('tp', 'TP'), ('sl', 'SL'), ('', 'None')], default='', max_length=8),
        ),
    ]
