# Generated by Django 5.0.7 on 2026-07-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_marketsignal_actual_pnl_marketsignal_pnl_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsignal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=16),
        ),
    ]
