# Generated by Django 5.0.7 on 2026-07-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_marketsignal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsignal',
            name='news_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketsignal',
            name='news_sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
