# Generated by Django 5.0.7 on 2026-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_marketsignal_completed_at_exit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsignal',
            name='htf_advice',
            field=models.TextField(blank=True, default=''),
        ),
    ]
