# Generated by Django 5.2.17 on 2026-09-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_marketsignal_htf_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsignal',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
